name = "candle-haven"
compatibility_date = "2026-02-21"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "candledb"
database_id = "9a59058c-e121-4643-9712-3abc25aa2557"
